theme: jekyll-theme-minimal
title: <font size="3" style="font-family:Comic Sans MS;" color="Black"> Physics Mathematics Engineering Robotics </font>
link-col: "#FFFFFF"
hover-col: "#FFFFFF"
footer-col: "#FFFFFF"
footer-text-col: "#FFFFFF"
footer-link-col: "#FFFFFF"
email: omkarbhoite2013@gmail.com
