.typewriter h1 {
  overflow: hidden; /* Ensures the content is not revealed until the animation */
  border-right: .15em solid orange; /* The typwriter cursor */
  white-space: nowrap; /* Keeps the content on a single line */
  margin: 0 auto; /* Gives that scrolling effect as the typing happens */
  letter-spacing: .15em; /* Adjust as needed */
  animation: 
    typing 3.5s steps(40, end),
    blink-caret .75s step-end infinite;
}

/* The typing effect */
@keyframes typing {
  from { width: 0 }
  to { width: 100% }
}

/* The typewriter cursor effect */
@keyframes blink-caret {
  from, to { border-color: transparent }
  50% { border-color: orange; }
}
title: <font size="3" style="font-family:Comic Sans MS;" color="Black"> <marquee behavior="alternate" scrollamount="10">Physics</marquee> <br> <marquee behavior="alternate" scrollamount="12">Mathematics</marquee> <br> <marquee behavior="alternate" scrollamount="14">Engineering</marquee> <br> <marquee behavior="alternate" scrollamount="16">Robotics</marquee><br><div class="typewriter"> <h1>The cat and the hat.</h1></div></font>
link-col: "#FFFFFF"
hover-col: "#FFFFFF"
footer-col: "#FFFFFF"
footer-text-col: "#FFFFFF"
footer-link-col: "#FFFFFF"
email: "omkarbhoite2013@gmail.com"
