theme: jekyll-theme-minimal
title: Omkar Bhoite
navbar-col: "#FFFFFF"
navbar-text-col: "#FFFFFF"
navbar-children-col: "#FFFFFF"
page-col: "#FFFFFF"
link-col: "#FFFFFF"
hover-col: "#FFFFFF"
footer-col: "#FFFFFF"
footer-text-col: "#FFFFFF"
footer-link-col: "#FFFFFF"
